### PR TITLE
Fix #52

### LINKED ISSUE #52: Update README and docs for running nf-flu test profiles for Nanopore and Illumina platforms
README is out-of-date and there is no `test` profile anymore. nf-flu can be run with either a `test_illumina` or `test_nanopore` profile. Docs and README need to be updated to reflect this.

See related issue https://github.com/peterk87/nf-flu/issues/18

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug/Issue

Test profile is not working

### Nextflow command-line

```shell
nextflow run CFIA-NCFAD/nf-flu -profile test,docker
```

### Error Message

```shell
N E X T F L O W  ~  version 23.04.3
Pulling CFIA-NCFAD/nf-flu ...
 downloaded from https://github.com/CFIA-NCFAD/nf-flu.git
Unknown configuration profile: 'test'
```

### Workflow Version

3.3.5

### Nextflow Executor

local

### Nextflow Version

23.04.3.5875

### Java Version

11.0.20.1

### Hardware

Desktop

### Operating System (OS)

Ubuntu 22.04

### Conda/Container Engine

Docker

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by peterk87**
This PR fixes #52 
* updates the usage docs and README to show how to run Illumina and Nanopore test profiles
* the `test_nanopore` profile has been updated to use the samplesheet.csv at https://github.com/CFIA-NCFAD/nf-test-datasets/blob/nf-flu/samplesheet/samplesheet_test_nanopore_influenza.csv

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [X] If you've fixed a bug or added code that should be tested, add tests!
- [X] Ensure the test suite passes (`nextflow run . -profile test_nanopore,docker`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [X] `CHANGELOG.md` is updated.
- [X] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nhhaidee** [comment]
@peterk87 Do we need to handle case as below? 

ERR6359501	/path_to/nanopore_reads/run1

**Comment by peterk87** [comment]
> @peterk87 Do we need to handle case as below?
> 
> ERR6359501 /path_to/nanopore_reads/run1

It's handled in the CI workflow.

**Comment by nhhaidee** [comment]
OK

**Comment by nhhaidee** [comment]
In my changes, a new process was created to handle all cases the same as the CI workflow. But just for the local test, it is OK with me.

**Comment by peterk87** [comment]
Having tests and test data separate from the main codebase and core logic is preferred.

One solution would be to adopt [nf-test](https://code.askimed.com/nf-test/docs/getting-started/) for testing specific processes, workflows and the entire pipeline itself with the proper setup.

**Pull request merged**
